# Generated by Django 5.1.4 on 2025-02-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemcategory_alter_product_condition_item_itemimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('footwear', 'Foot Wear'), ('sports_wear', 'sports_wear'), ('jewelery', 'Jewelery'), ('Fashion', 'fashion'), ('cologne', 'Cologne'), ('Toys', 'toys'), ('health&beauty', 'Health&Beauty'), ('furniture', 'Furnitures'), ('spareparts', 'Spare_parts'), ('electronics', 'Electronics'), ('phones&tablets', 'Phones&Tablets')], default='new', max_length=20),
        ),
    ]
