# Generated by Django 5.1.4 on 2025-02-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
    ]
