# Generated by Django 5.1.4 on 2025-02-10 11:25

import django.core.validators
import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='product',
        ),
        migrations.AddField(
            model_name='item',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='item',
            field=models.ForeignKey(default=inventory.models.get_default_item, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
