# Generated by Django 5.1.4 on 2025-02-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_category_remove_product_user_and_more'),
        ('orders', '0003_remove_orderitem_product_orderitem_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
