# Generated by Django 5.1.4 on 2025-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
