# Generated by Django 5.1.4 on 2025-02-10 11:25

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_category_remove_product_user_and_more'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Item',
            field=models.ForeignKey(default=orders.models.get_default_item, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
